pipeline {
    agent { label 'docker' }

    stages {
        stage('Build') {
            steps {
                dir('app') {
                    sh 'docker build -t naveen352/settlement-batch-processor:latest .'
                }
            }
        }

        stage('Test') {
            steps {
                sh 'docker run --rm naveen352/settlement-batch-processor:latest npm test'
            }
        }

        stage('Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-cred',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push naveen352/settlement-batch-processor:latest
                    '''
                }
            }
        }
    }
}
