apiVersion: v1
kind: Service
metadata:
  name: transaction-audit
  namespace: {{ .Values.namespace }}
  labels:
    app: transaction-audit
spec:
  type: {{ .Values.service.type }}
  selector:
    app: transaction-audit
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
