replicaCount: 2

namespace: fintech

image:
  repository: naveen352/transaction-audit
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 5000

serviceAccount:
  name: transaction-audit
  # Fill in with the irsa_role_arn Terraform output
  roleArn: "arn:aws:iam::593241949985:role/finedge-transaction-audit-irsa-role"

auditBucket: transaction-bucket-naveen-issue-eight

service:
  type: ClusterIP
  port: 80

ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
  host: transaction-audit.finedge.internal

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
